### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Tekn1ck** [melowntech/vts-browser-unity-plugin#17] opened 2020-07-24 07:56 UTC
Hi, 

I have a couple of questions. How do we change the shader on the streamed data? We have a vts server running with photogrammetry data and want to change the shader type from unlit opaque to other types to test.

Secondly is it possible to make this run in HDRP? So far we have had no luck - is it a case of changing the shaders?

Thanks

**Comment by Tekn1ck** [comment] 2020-07-25 07:58
OK. So worked out how to change the shaders, but now looking into HDRP. Any pointers would be super helpful!

Thanks

**Comment by malytomas** [comment] 2020-07-27 09:07
Hi,
I have just committed an example scene with changed shaders (surface shaders) and added a sun.
I will try the HDRP and will let you know.

**Comment by Tekn1ck** [comment] 2020-07-28 00:42
Thanks very much - I will take a look at this today. We will be so excited to get into HDRP do let me know how you get on with that.

**Comment by malytomas** [comment] 2020-07-28 14:17
I gave it a quick look and it seems that the shaders have to be remade in the node editor.

If I were to do it, I would have to make it work in all scriptable pipelines, not just HDRP.
Also all the variants would have to be supported (unlit / shadowed / surface).

Another challange is the atmosphere. This is rather complicated on its own and making it work with all the pipelines etc. would be an enormous task.

Unfortunately, I do not have time for all that at the moment. Therefore I will have to leave this on you now. That said, I would be delighted if you would let me know if you do make any progress. Thanks.

**Comment by malytomas** [comment] 2020-07-28 14:19
If you decide to do this, feel free to ask further questions about how specific things works.

**Comment by Tekn1ck** [comment] 2020-07-28 22:41
So for us we just need Lit, unlit, Unlit with shadows and Unlit in HDRP. We will be disabling the atmosphere anyway since we use a different system. When you say node editor, do you mean remake the materials in Shader Forge and then reconnect the albedo map into the correct map channel and then save this shader then make a new material prefab? We are converting SLPK to VTS on the server side so is there anything we should look out for and could it support PBR too?

**Comment by malytomas** [comment] 2020-07-29 08:31
> So for us we just need Lit, unlit, Unlit with shadows and Unlit in HDRP. We will be disabling the atmosphere anyway since we use a different system.

I think that is much more manageable.

> When you say node editor, do you mean remake the materials in Shader Forge and then reconnect the albedo map into the correct map channel and then save this shader then make a new material prefab?

Yes, I think that summarizes it well.
The shader has to correctly handle two uv channels, two textures (albedo and mask), uv-space clipping, dithering with the noise texture and perhaps some more that I am forgetting now. There is also a bunch of configuration variables coming in a uniform parameter (grayscale, noise texture index, etc.). Look into the other shaders for how to make it.

> We are converting SLPK to VTS on the server side so is there anything we should look out for and could it support PBR too?

VTS material system is, unfortunately, quite lacking in this regard now. Currently only the diffuse (albedo) texture is supported. We have plans for expanding this into full PBR, but that is still miles away.

**Comment by Tekn1ck** [comment] 2021-03-24 03:02
Hi again.

So we have updated the shaders to HDRP and it is looking pretty good - but we have a problem with LODS loading really strangely. It seems like they are loading the lowest LOD at the same time as higher ones and also unloading LODS before the next highest level has finished loading. It does not do this in the Standard Render pipe and our shader programmer confirms it is not the shader itself but something within the VTS code.

https://vimeo.com/528123502/0e68f048ec

I wonder if you could tell me if you have any ideas why this is acting like this and where to look for a solution?

**Comment by malytomas** [comment] 2021-03-24 09:15
Hi,

Congratulations on the progress :D

VTS browser does lod blending. It is controlled by camera option lodBlending and accepts values 0 - no blending, 1 - simple blending, and 2 - blending with screen edge detection. You may try disabling it to verify that the problem is connected to it.

Assuming it is related, the shaders probably have to handle property DrawSurfaceBase.blendingCoverage.

In the provided shaders, it is handled by comparing with blue noise texture:
```
if (_BlendingCoverage > -0.5) \
	{ \
		float4 cp = ComputeScreenPos(i.pos); \
		float3 uv = float3(cp.xy, _FrameIndex % 16); \
		float smpl = UNITY_SAMPLE_TEX2DARRAY_LOD(_BlueNoiseTex, uv, 0); \
		if (_BlendingCoverage < smpl) \
			clip(-1.0); \
	} \
```

Another option is to multiply it with opacity, however, transparency is usually more problematic.

Let me know if that helps.

Best, tm

**Comment by Tekn1ck** [comment] 2021-03-24 12:08
Like this?

![image](https://user-images.githubusercontent.com/67991497/112308010-be267680-8cf5-11eb-871d-d17f86bfef4d.png)

**Comment by malytomas** [comment] 2021-03-24 13:09
Example:
```json
{ "maxTexelToPixelScale":1.2, "cullingOffsetDistance":100, "lodBlending":2 }
```

On a Camera object.

**Comment by Tekn1ck** [comment] 2021-03-25 03:05
Hi Tomas, 
So the blending mode is working, but it is not really fixing the LOD popping effect. The problem you can see in this video linked below. Even when a higher detail LOD is loaded for some reason VTS thinks it should load a lower detail LOD over the top which does not make sense. It also unloads the Less Detailed LOD before the next higher detail LOD is loaded. 

https://vimeo.com/528609833/3bc6cfdf0e

Below you can also see more clearly that as the camera swings from left to right the LOD0 keeps popping in over the top of the LOD5 which is a bit weird because the higher detail LOD is already loaded.

https://vimeo.com/528629560/9de60d4780

I do not think this is a shader issue any more. Have you any suggestions on how we deal with these visual artifacts?

I have played a little bit with the camera settings, but not much luck so far. 

I have this so far:

{ "traverseModeSurfaces":"balanced", "traverseModeGeodata":"none", "maxTexelToPixelScale":1.2, "cullingOffsetDistance":250, "lodBlending":2 }

**Comment by malytomas** [comment] 2021-03-25 09:19
>I do not think this is a shader issue any more. Have you any suggestions on how we deal with these visual artifacts?

Unless you can replicate the issue with the standard shaders I will assume that it is caused by the shaders.

Do you have the clipping code based on uv coordinates?

```
#if defined(SHADER_API_GLCORE) || defined(SHADER_API_GLES) || defined(SHADER_API_GLES3)
#	define VTSH_MANUAL_CLIP 1
#endif

#ifdef VTSH_MANUAL_CLIP
#	define VTSH_V2F_CLIPPING \
		float4 clip : TEXCOORD2;
#	define VTS_FRAG_CLIPPING(i) \
		if (any(i.clip <= 0.0)) \
			clip(-1.0);
#else
#	define VTSH_V2F_CLIPPING \
		float4 clip : SV_ClipDistance0;
#	define VTS_FRAG_CLIPPING(i)
#endif
```

**Comment by Tekn1ck** [comment] 2021-03-25 09:27
ok - we will take another look. It could be an HDRP thing too.

**Comment by merpheus-dev** [comment] 2021-03-25 13:48
> Unless you can replicate the issue with the standard shaders I will assume that it is caused by the shaders.
> 
> Do you have the clipping code based on uv coordinates?
> 

Hi Tomáš, I am working on the HDRP port of VTS shaders to HDRP. So simply, we have a blending and clipping code as follows:
`		float4 color;

		if (any(d.texcoord2 <= 0.0)) 
			clip(-1.0);

		color = tex2D(_MainTex, d.texcoord3.xy); 
		if (getFlag(0)) 
		{ 
			if (tex2D(_MaskTex, d.texcoord3.xy).r < 0.5) 
				clip(-1.0); 
		} 
		if (_BlendingCoverage > -0.5) 
		{ 
			float4 cp = d.screenPos;
			float3 uv = float3(cp.xy, _FrameIndex % 16); 
			float smpl = UNITY_SAMPLE_TEX2DARRAY_LOD(_BlueNoiseTex, uv, 0); 
			if (_BlendingCoverage < smpl) 
				clip(-1.0); 
		} 
		if (getFlag(1)) 
			color = color.rrra; 
		color *= _Color;`

some of the variables like clip is replaced with the texcoord2 for example, because of the way HDRP accepts data. But they should work the same.
As can be seen from earlier videos that my colleague shared, blue noise sampling to blend between LODs is working. Also for clipping we use 
`if (any(d.texcoord2 <= 0.0)) 
			clip(-1.0);`

which should work the same with Built In. I was mostly suspected about the fact that the way HDRP handles camera matrices and that might not be accounted by VTS plugin. But open to any suggestions.

**Comment by malytomas** [comment] 2021-03-25 14:41
Hi Mert,

the code looks good to me.

Some ideas to try out:

1) disabling lod blending `"lodBlending":0` the issue is still there, right?

2) changing traversal mode `"traverseModeSurfaces":"flat"` or `"traverseModeSurfaces":"stable"` or `"traverseModeSurfaces":"hierarchical"`
https://github.com/melowntech/vts-browser-cpp/blob/d8111d02b804b36da1fea29898b049cb861e1dfa/browser/src/vts-libbrowser/include/vts-browser/foundation.hpp#L95
these modes do not depend on the uv clipping so that could help narrow down the problem.

3) try visualizing some of the properties eg. `color.xy = d.texcoord1.xy` - this should make tiles very clearly visible.
`color.xy = _UvClip.xy` - see if this does anything. It should change color for tiles that need clipping.
Similarly `color.xy = _UvClip.zw`.

Best,
tm

**Comment by merpheus-dev** [comment] 2021-03-28 20:14
Okay, it seems like tiles really load late from what I understand, with lodblending:0, issue is still in place yes.
We tried flat, stable and hierarchical, seems like tiles are loading late.
Also I tried your suggestions about visualasation and seems like tiles are loading late from what I can see. Here are some videos:

`color.xy = d.texcoord1.xy`


https://user-images.githubusercontent.com/3215742/112766550-f9d57f00-901a-11eb-93d9-f4842c6e624e.mp4

`color.xy = _UvClip.xy`

https://user-images.githubusercontent.com/3215742/112766603-2ee1d180-901b-11eb-9569-702e1e16714c.mp4

`color.xy = _UvClip.zw`

https://user-images.githubusercontent.com/3215742/112766651-4e78fa00-901b-11eb-91cc-5ef6912d84eb.mp4

**Comment by malytomas** [comment] 2021-03-29 09:42
All the visualizations shows that the values in shaders are correctly available.

In fact, I do not see the issue in these 3 videos - sure tiles take some time to load, that is inevitable, but I found none of the weird overlapping tiles as was seen in previous videos.

Have you changed any other code in vts apart from shaders?

**Comment by merpheus-dev** [comment] 2021-03-29 11:02
Not really, plus I only hand off the shaders, so @Tekn1ck can try with their setup w/o any issue. 

But I think there might be a weirdness going on with how HDRP handles regular VTS code, perhaps camera matrices, material property block etc. Not quite sure. 

If you just add VTS to an HDRP project, it should work, and the issue should be there. You only need to change SurfaceOpaque material to HDRP Lit shader and only change one line in VTS code,
`shaderPropertyMainTex = Shader.PropertyToID("_MainTex");` in VTSCameraBase.cs line 51
Should be:
`shaderPropertyMainTex = Shader.PropertyToID("_BaseColorMap");` so it can send albedo to lit shader.

**Comment by merpheus-dev** [comment] 2021-03-31 13:32
> All the visualizations shows that the values in shaders are correctly available.
> 
> In fact, I do not see the issue in these 3 videos - sure tiles take some time to load, that is inevitable, but I found none of the weird overlapping tiles as was seen in previous videos.
> 
> Have you changed any other code in vts apart from shaders?

any ideas?

**Comment by Tekn1ck** [comment] 2021-04-01 04:20
@malytomas nothing has changed in the project apart from the shaders themselves. What we see are two distinct artifacts as below. These are probably connected to the same issue, but we do not know what this is. 

I will email the shaders to you, perhaps you can see better what the problem is if you can see what is happening for yourself. Perhaps this will be faster.

![image](https://user-images.githubusercontent.com/67991497/113242085-d00ea780-92fb-11eb-92f8-3165acf3eb92.png)

**Comment by malytomas** [comment] 2021-04-01 10:21
I have received the email with the shaders.
What version of unity do you use? I see 2019.4 in the video title but the shaders have 2020 suffix.
Are there different versions of the hdrp pipeline?
Also, what version of vts do you use? Is it from unity store or custom build?
I will try the shaders as soon as I have some time..

**Comment by Tekn1ck** [comment] 2021-04-01 11:14
Hi, we are actually starting to use 2021.1 now since some of our other software depends on it.

**Comment by malytomas** [comment] 2021-04-06 13:03
> You only need to change the material of VtsSurfaceOpaque to HDRP/Lit.

May I ask what do you mean by this?

**Comment by merpheus-dev** [comment] 2021-04-06 19:18
> > You only need to change the material of VtsSurfaceOpaque to HDRP/Lit.
> 
> May I ask what do you mean by this?

In Shaders scene that comes with Vts, there is default VtsSurfaceOpaque and VtsSurfaceTransparent materials that is attached to scripts, so changing that material from old Built-in shader to hdrp lit material should also show the issue even without custom shaders. Thats what I meant. Sorry if it was a bit vague.

**Comment by malytomas** [comment] 2021-04-07 08:51
> changing that material from old Built-in shader to hdrp lit material should also show the issue even without custom shaders.

Of course changing that to any built-in shaders would show issues. Custom shaders is mandatory requirement with vts.

Anyway, I am now testing the shaders you sent - more on that in private email.

**Comment by merpheus-dev** [comment] 2021-04-07 10:27
> Of course changing that to any built-in shaders would show issues. Custom shaders is mandatory requirement with vts.
Sorry, I was under the impression that the problem is vts choosing which lods to load is bugged, rather than shader not able to do the smooth blend at the right time.

**Closed** 2022-03-07 09:57 UTC
